# Generated by Django 2.0 on 2018-04-05 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Опис')),
                ('text', models.TextField(blank=True, max_length=2500, verbose_name='Текст')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Ціна')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='catalogue/images/gallery', verbose_name='Зображення')),
                ('is_title', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalogue.Article', verbose_name='зображення')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('not_registered_user', models.CharField(max_length=100, verbose_name='незареєстрований користувач')),
                ('creator', models.CharField(default='Анонім', max_length=100, verbose_name='автор відгуку')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Текст')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('moderated', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalogue.Article', verbose_name='відгук')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
