# Generated by Django 2.0 on 2018-01-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20180128_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
