# Generated by Django 2.0 on 2017-12-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20171209_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='Зображення',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='Назва',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='Опис',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='Текст',
        ),
    ]
