# Generated by Django 2.0 on 2017-12-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20171210_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Опис',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Зображення',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Назва',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Текст',
            new_name='text',
        ),
    ]
