# Generated by Django 2.0 on 2017-12-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20171210_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='150x150px', upload_to='catalogue/images', verbose_name='Зображення'),
        ),
    ]
