# Generated by Django 2.0 on 2018-01-16 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_article_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='catalogue/images/gallery', verbose_name='Зображення')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalogue/images', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='articleimages',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Article', verbose_name='стаття'),
        ),
    ]
